# Generated by Django 4.2.30 on 2026-08-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationtarget',
            options={'ordering': ['asset']},
        ),
        migrations.AlterModelOptions(
            name='monthlycontribution',
            options={'ordering': ['-month', 'asset']},
        ),
        migrations.RemoveConstraint(
            model_name='monthlycontribution',
            name='unique_month_asset',
        ),
        migrations.AlterUniqueTogether(
            name='monthlycontribution',
            unique_together={('month', 'asset')},
        ),
    ]
